webapp/urls.py
from django.contrib import admin
from django.urls import path
from crudapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp',views.emp),
    path('show/',views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.delete),
]

crudapp/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    eid = models.IntegerField(default=None)
    name = models.CharField(max_length=20)
    email = models.EmailField()
    contact = models.CharField(max_length=15)

    class Meta:
        db_table = "employee"

crudapp/forms.py
from django import forms
from crudapp.models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

crudapp/views.py
from django.shortcuts import render,redirect
from crudapp.forms import EmployeeForm
from crudapp.models import Employee

# Create your views here.

def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("/show")
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, "index.html", {'form': form})

def show(request):
    employees = Employee.objects.all()
    return render(request,"show.html", {'employees': employees})


def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request,"edit.html",{'employee': employee})

def update(request,id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance = employee)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request, "edit.html", {'employee':employee})

def delete(request,id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect('/show')

crudapp/templates/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Index</title>
        {% load static %}
        <link rel="stylesheet" href="{% static '/style.css'%}"/>

    </head>
    <body>
        <form action="/emp" method="POST" class="post-form">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3> Update Details </h3>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Employee ID:</label>
                <div class="col-sm-4">
                   <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{employee.eid}}">
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Employee Name:</label>
                <div class="col-sm-4">
                    <input type="text" name="name" id="id_ename" required maxlength="100" value="{{employee.name}}">
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Employee Email:</label>
                <div class="col-sm-4">
                    <input type="text" name="email" id="id_email" required maxlength="254" value="{{employee.email}}">
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Employee Contact:</label>
                <div class="col-sm-4">
                    <input type="text" name="contact" id="id_contact" required maxlength="20" value="{{employee.contact}}">
                </div>
            </div>

            <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
             <button type="submit" class="btn btn-primary"> Update</button>
            </div>
        </div>



        </div>
        </form>
    </body>
</html>

crudapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Index</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static '/style.css%}"/>

    </head>
    <body>
        <form action="/emp" method="POST" class="post-form">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>
                        Enter Details
                    </h3>
                </div>
            </div>

            div class="form-group row">
                <label class="col-sm-1 col-form-label">Employee ID:</label>
                <div class="col-sm-4">
                    {{ form.eid }}
                </div>
            </div>

            div class="form-group row">
                <label class="col-sm-1 col-form-label">Employee Name:</label>
                <div class="col-sm-4">
                    {{ form.name }}
                </div>
            </div>

            div class="form-group row">
                <label class="col-sm-1 col-form-label">Employee Email:</label>
                <div class="col-sm-4">
                    {{ form.email }}
                </div>
            </div>

            div class="form-group row">
                <label class="col-sm-1 col-form-label">Employee Contact:</label>
                <div class="col-sm-4">
                    {{ form.contact }}
                </div>
            </div>

            div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
             <button type="submit" class="btn btn-primary"> Submit</button>
            </div>
        </div>



        </div>
        </form>
    </body>
</html>

crudapp/templates/show.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Index</title>
        {% load static %}
        <link rel="stylesheet" href="{% static '/style.css'%}"/>

    </head>
   <body>
     <table class="table table-striped table-bordered table-sm">
         <thead class="thead-dark">
             <tr>
                 <th> Employee Id</th>
                 <th> Employee Name</th>
                 <th> Employee Email</th>
                 <th> Employee Contact </th>
                 <th> Actions</th>
             </tr>

         </thead>
         <tbody>
            {% for employee in employees %}
            <tr>
                <td> {{ employee.eid }}</td>
                <td> {{ employee.name }}</td>
                <td> {{ employee.email }}</td>
                <td> {{ employee.contact }}</td>
                <td>
                    <a href="/edit/{{ employee.id }}">
                        <span class="glyphicon glyphicon-pencil"> Edit</span>
                    </a>
                    <a href="/delete/{{ employee.id }}"> Delete</a>
                </td>

            </tr>
            {% endfor %}
         </tbody>

     </table>  
     <br>
     <br>
     <center>
         <a href="/emp" class="btn btn-primary">Add new record</a>
     </center>

   </body>
   </html>